In [3]:
## 网址
### http://freemind.pluskid.org/machine-learning/softmax-vs-softmax-loss-numerical-stability/

In [61]:
import numpy as np
import random
def softmax(a):
    a = a - a.max()
    x = np.exp(a)
    
    return x/np.sum(x, axis=1,keepdims=True)

x=np.random.rand(2,3)

print np.sum(x, axis=1,keepdims=True).shape
print np.sum(x, axis=1).shape

x_prob = softmax(x)
print x_prob, x_prob.sum(axis=1)



(2, 1)
(2,)
[[ 0.31350267  0.43284544  0.25365189]
 [ 0.38646305  0.22437274  0.38916421]] [ 1.  1.]


In [62]:
x=np.random.rand(1,4)
def gradient_together(z, y):
    o = softmax(z)
#     print o
    o[0,y] = o[0,y] - 1.0
    return o


def gradient_separated(z, y):
    o = softmax(z)
    b = np.eye(o.shape[1])
#     print o.shape
#对角阵
    for i in range(o.shape[1]):
        b[i][i] = o[0][i]
#     print o
#     print b
#     print o*o.T
    
    oz = b - o*o.T
    fo = np.zeros((o.shape[1],1))
#     print fo.shape
    fo[y][0] = -1.0/o[0][y]
    return oz.dot(fo).T
print "111111111111111111"

111111111111111111


In [64]:
print x
x[0][2] = -1e38
print x
print gradient_together(x, 2)
print gradient_separated(x, 2)  

[[ 0.07316147  0.18829738  0.86373641  0.33271995]]
[[  7.31614708e-02   1.88297376e-01  -1.00000000e+38   3.32719952e-01]]
[[ 0.29253593  0.3282329  -1.          0.37923117]]
[[ nan  nan  nan  nan]]


/home/roger/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:22: RuntimeWarning: divide by zero encountered in double_scalars
