In [1]:
from mxnet import ndarray as nd

In [2]:
nd.ones((3,4))


[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
<NDArray 3x4 @cpu(0)>

In [3]:
y = nd.random_normal(0,1,shape=(3,4))

y


[[ 2.21220636  1.16307867  0.7740038   0.48380461]
 [ 1.04344046  0.29956347  1.18392551  0.15302546]
 [ 1.89171135 -1.16881478 -1.23474145  1.55807114]]
<NDArray 3x4 @cpu(0)>

In [9]:
x = nd.ones((3,4))
y = nd.ones((3,4))

before = id(y)
y  += x
id(y) == before

True

In [7]:
z = nd.zeros_like(x)
before = id(z)
z[:] = x+y
id(z) == before


True

In [11]:
import mxnet.autograd as  ag
x = nd.array([[1,2],[3,4]])
x.attach_grad()
with ag.record():
    y = x*2
    z = y*x
z.backward()
x.grad


[[  4.   8.]
 [ 12.  16.]]
<NDArray 2x2 @cpu(0)>

In [12]:
x


[[ 1.  2.]
 [ 3.  4.]]
<NDArray 2x2 @cpu(0)>

In [13]:
nd.norm(x)


[ 5.47722578]
<NDArray 1 @cpu(0)>

In [14]:
x



[[ 1.  2.]
 [ 3.  4.]]
<NDArray 2x2 @cpu(0)>